version: "3"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: .env
  db:
    image: "couchdb"
    ports:
      - "5984:5984"
    env_file: .env